server:
  port: 8081

#spring:
#  dubbo:
#    application:
#      name: spring-dubbo-provider
#    registry: zookeeper://strongyang.com:2181
#    server: true

dubbo:
  application:
    #应用名称，每个dubbo应用的名称都是唯一的
    name: spring-dubbo-provider
  registry:
    #注册中心
    address: zookeeper://strongyang.com:2181
  protocol:
    #协议名称
    name: dubbo
    #服务暴露端口
    port: 20880
  scan:
    #扫描服务注册bean,即service实现类所在的包
    basePackages: com.springframework.sf.dubbo.provider.rpc
